### ISSUE TITLE
Seg Fault on 2008 r2 sp1

### ISSUE THREAD

**Issue by neil-wwt** [microsoft/etl2pcapng#26]
Tried running v1.3.0 from 2008 r2 sp1 and it crashes. See screenshots.

![Crash error message](https://user-images.githubusercontent.com/22230865/91778499-ea3ea680-ebaf-11ea-9736-08b3261b78ee.png)

![OS Version info](https://user-images.githubusercontent.com/22230865/91778498-e90d7980-ebaf-11ea-9d4f-96b0cf35871f.png)

**Comment by walter-1** [comment]
Windows 2008 R2 is **no more supported**! (see https://support.microsoft.com/en-us/help/4456235/end-of-support-for-windows-server-2008-and-windows-server-2008-r2)

**Comment by maolson-msft** [comment]
This is issue is the same as #21
