### ISSUE TITLE
Fails To Convert Packets

### ISSUE THREAD

**Issue by sammycoolster** [microsoft/etl2pcapng#29]
This version of etl2pcapng is failing to convert the packets at all that is captured using netsh. Have tried from multiple machines as well. Do we know what could be the issue. 

![image](https://user-images.githubusercontent.com/46014359/92627014-c60e5400-f298-11ea-9327-162d76ba4670.png)

**Comment by sammycoolster** [comment]
I tested with the latest version and this issue is not present anymore, and am able to convert the packets. This one can be closed. However, do we know why the last version did not work ?

**Comment by csujedihy** [comment]
The latest version = 1.4.0?

**Comment by sammycoolster** [comment]
Yes, that is correct. With version 1.4.0 the issue is not seen and things are working well.

**Comment by csujedihy** [comment]
Can you share the etl file?
