### ISSUE TITLE
Converted 0 frames

### ISSUE THREAD

**Issue by markuchi** [microsoft/etl2pcapng#30]
Using version 1.4.
Server 2019, always says converted 0 frames.

**Comment by johnmagee-waystar** [comment]
Windows 10 same issue with converted 0 frames

**Comment by brianlance** [comment]
Windows 10 here with the same issue. Tried 1.3.0 and got the same results.

**Comment by Sleepw4lker** [comment]
Same here, Windows 2019 and Windows 10 (2004).

**Comment by Kreijstal** [comment]
Windows 10 as well, converted 0 frames.

**Comment by csujedihy** [comment]
Can anyone of you share an etl file?
