### ISSUE TITLE
Unable to download file

### ISSUE THREAD

**Issue by robert-poreba** [microsoft/etl2pcapng#37]
Hi,
Downloading the .zip file from the below gives virus/malware error in both Chrome and Firefox. Is this expected?
https://github.com/microsoft/etl2pcapng/releases/tag/1.50

**Comment by vidarak** [comment]
Also triggers alert from Windows Defender for trojan. Win32/Dridex!ml

**Comment by csujedihy** [comment]
I believe it's a false positive.

**Comment by vidarak** [comment]
@maolson-msft Would suggest to re-release one that doesn't trigger a false positive. None of the older versions I tried has this issue. Perhaps include a scan with Windows Defender into your build pipeline?
