### ISSUE TITLE
Arp packets to large after conversion

### ISSUE THREAD

**Issue by roodec** [microsoft/etl2pcapng#41]
ls, 

At the moment of writing the following seems to occur when I convert an elt trace file to an pcapng file there appears  to be a problem converting the arp packets. There are represented to be over 2G in size. If i do a live capture on the same server with wireshark or netmon the arp packets are normal size.

**Comment by maolson-msft** [comment]
@roodec , please share:
-an example .etl file that reproduces this problem
-the packet number of the problematic ARP
-the version of etl2pcapng that you saw this problem with.

Thanks
