### ISSUE TITLE
Using GitHub Actions to automate releases

### ISSUE THREAD

**Issue by pratikpc** [microsoft/etl2pcapng#47]
Hey we could use GitHub Actions to automate building and releasing the project itself.

Given that git tags are already being used, I would recommend something in which the maintainers will have to create a tag after which a GitHub Action will execute and perform the deployment

Is that something which the maintainers would interested in?

**Comment by thhous-msft** [comment]
Thats something that could potentially be looked into. For now though, I've added actions automation for building in https://github.com/microsoft/etl2pcapng/pull/52

**Comment by nibanks** [comment]
I don't think it'd be awful to have tags trigger the GitHub release creation.

**Comment by maolson-msft** [comment]
The plan is to have all future releases prod signed (I'm already in the process of getting binaries signed for a new release). That signing is a manual process as far as I know.

The Actions are nice for checking build though (and I have been thinking about adding a test as well).

**Comment by maolson-msft** [comment]
Since we now have a build action, and prod signing in github actions isn't possible AFAIK, I'm marking this done.
