### ISSUE TITLE
released version should be dropped in zip format Etl2Pcapng.zip

### ISSUE THREAD

**Issue by walter-1** [microsoft/etl2pcapng#61]
The Explorer plugin from James Kehr at https://github.com/microsoft/Convert-Etl2Pcapng expects to see a **.zip** file on the release server (https://github.com/microsoft/etl2pcapng/releases)

Can you please post the compressed **Etl2Pcapng.zip** there again? Thanks.

Reason: all engineers having installed the Explorer plugin are failing to convert ETL files to Wireshark pcap format after version 1.9.0 had been released.

**Comment by maolson-msft** [comment]
Thanks for the report Walter.

@JamesKehr I switched from the current zipfile-with-two-archs drop format to just dropping the 64-bit binary. How inconvenient is it for your wrapper to deal with this change?

**Comment by JamesKehr** [comment]
It won't be a problem. I just need to earmark a couple of hours to update the code.

**Comment by maolson-msft** [comment]
Good to hear! I'll leave this Issue open until then.

**Comment by JamesKehr** [comment]
An updated module has been published to the PowerShell Gallery.

https://www.powershellgallery.com/packages/Convert-Etl2Pcapng/2022.11.22

https://github.com/microsoft/Convert-Etl2Pcapng

Please let me know if you run into any issues.

**Comment by maolson-msft** [comment]
@walter-1, how's it look?

**Comment by walter-1** [comment]
**Great**! appreciate all combined efforts and agree resolving this issue.
FYI: `Update-Module `did the trick for me to make the installed plug-in work again! Thanks James!
```
PS C:\TSSv2> Update-Module

Untrusted repository
You are installing the modules from an untrusted repository. If you trust this repository, change its InstallationPolicy value by running the Set-PSRepository cmdlet. Are you sure you want to install the modules from 'PSGallery'?
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "N"): A
```

**Comment by dgcom** [comment]
I would vote to keep zip file - many places have policy to prevent .exe download, but allow .zip files.

**Comment by ViDou83** [comment]
It works for me as well, and what a surprise to see the speed of trace conversion! That will drop my coffee consumption for sure :)

**Comment by nibanks** [comment]
I propose the following instead of including the zip: https://github.com/microsoft/etl2pcapng/issues/63. This will make it very trivial to install on Windows: `winget install etl2pcapng`.

**Comment by dgcom** [comment]
Installing with package manager is not helping people, who cannot download executables from the web. Places which prohibit that won't allow unrestricted package managers either.
