### ISSUE TITLE
Make output file name an optional command-line parameter

### ISSUE THREAD

**Issue by justinsapp** [microsoft/etl2pcapng#67]
It would be convenient for me if there was a default output filename that could be used instead of manually providing one.

For example, I would like to be able to run the command:
`etl2pcapng.exe trace.etl`

and get an output file called something like `trace.etl.pcapng`.

I'd be glad to help with the implementation if this sounds like a useful feature for others as well.

**Comment by maolson-msft** [comment]
@justinsapp- I've long considered this. Let's name the output file `trace.pcapng` rather than `trace.etl.pcapng`. Looking forward to your PR, thanks!

**Comment by justinsapp** [comment]
Cool, sounds like a plan! I'll hope to get that PR in soon.
